name: Build&Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Checkout
      uses: actions/checkout@v2
    - name: SonarScanner install
      run: dotnet tool install --global dotnet-sonarscanner
    - name: SonarScanner run
      run: dotnet sonarscanner begin /d:sonar.organization=raiffeisen-dgtl /d:sonar.projectKey=Raiffeisen-DGTL_ViennaNET /d:sonar.sources=. /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io /d:sonar.verbose=true /d:sonar.cs.nunit.reportsPaths="./TestResult/TestResults.xml" /d:sonar.cs.opencover.reportsPaths="./TestResult/coverage.opencover.xml"
    - name: Build
      run: dotnet publish -c Release --self-contained false
    - name: Test
      run: dotnet test --no-build --filter "TestCategory=Unit" --logger "nunit;LogFilePath=TestResult/TestResult-{assembly}.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover\" /p:CoverletOutput=TestResult/
    - name: Sonar End
      run: dotnet sonarscanner end
      
    #- name: SonarCloud Scan
    #  uses: sonarsource/sonarcloud-github-action@master
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
